name: buzzgrab
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  pin_code_fields: ^8.0.1

  html: ^0.15.4
  carousel_slider:
  flutter_slidable: ^4.0.0
  shimmer_pro:
  colorful_safe_area: ^1.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  fancy_shimmer_image: ^2.0.3
  file_picker: 9.2.1
  firebase_auth: ^4.15.3
  firebase_core:
  firebase_messaging:
  flutter_easyloading: ^3.0.5
  flutter_widget_from_html: ^0.16.0
  flutter_local_notifications: ^19.1.0
  shared_preferences: 2.2.2
  flutter_screenutil: ^5.9.3
  share_plus:
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in:
  image_cropper: ^10.0.0
  image_picker:
  in_app_review:
  logger: ^2.0.2+1
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.2
  intl: ^0.20.2
  flutter_logger:
    path: flutter_logger
  connectivity_plus: ^5.0.2
  smooth_page_indicator:
  dots_indicator:
  intl_phone_field:
  pinput: ^5.0.2
  camera:
  lottie: ^3.3.1
  flutter_html:
  fluttertoast: ^8.2.12
  dropdown_button2:
  #  local_auth: ^2.1.3
  permission_handler:
  shimmer:
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  dotted_border:
  auto_height_grid_view: ^1.0.0
  #  confetti: ^0.7.0
  flutter_chat_bubble:
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.5
  flutter_timezone: ^4.1.1
  open_file: ^3.5.10
  in_app_update:
  device_marketing_names: ^1.1.5
  google_maps_flutter: ^2.13.1
  flutter_polyline_points: ^3.1.0
  #  hyperpay_plugin:
#  in_app_update: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
#    - family: Corinthia
#      fonts:
#        - asset: assets/fonts/Corinthia-Regular.ttf

